Fix 'generator' object not subscriptable error
Function enumerate_workshop_mods() would throw
TypeError: 'generator' object not subscriptable when attempting
to access returned tuple using index subscript (ie. "os.walk(..)[2]"),
which was possibly caused by a python update. Fix by iterating over
generator tuples separately before iterating over third index of tuple.